### ISSUE TITLE
Remaping text-object bind doesn't work

### ISSUE THREAD

**Issue by Darukutsu** [akinomyoga/ble.sh#377]
**ble version**: 0.4.0-devel4+3f133936
**Bash version**: 5.2.21(1)-release

```
ble-bind -m 'vi_xmap' -f l vi-command/text-object
ble-bind -m 'vi_xmap' -f i vi-command/forward-char
```
when trying to select inner word, bracket etc. `vlw` (`viw` default) it does `vw` instead.

```
hello who are you
  ^ -cursor position
```
selects
```
he[llo w]ho are you
```

**Comment by akinomyoga** [comment]
Hmm, thanks for the report. With the current implementation, the text-object widget needs to be bound to either `a` or `i` because the widget needs to determine whether to include the surrounding characters. If you bind it to `l`, the widget cannot determine whether it should behave as if `a` or `i`, so the widget just fails.

Let me think about the design again.

**Comment by akinomyoga** [comment]
In commit 11cf118a, I have separated the widget `vi-command/text-object` into `vi-command/text-object-inner` and `vi-command/text-object-inner`. You can now bind it as

```bash
# blerc

ble-bind -m 'vi_xmap' -f l vi-command/text-object-inner
```

Could you update `ble.sh` by running `ble-update` in a ble.sh session and check if it works?

**Comment by Darukutsu** [comment]
Thanks :heart: , now it works.
It would be also cool if one could do reverse text-object search in some cases like in vim, although it's not needed for me. I can cope with `fF`.

for example

1. doing `vi'`, `va'` here will do nothing (should select bar)
```
echo 'foo' 'bar'
               ^
```

2. doing `vi'`, `va'` here will do nothing (should select foo)
```
echo 'foo' | less
                ^
```

3. doing `vi'`, `va'` here works
```
echo 'foo' | less
^

echo '[foo]' | less
```
Feel free to close the issue.

**Comment by akinomyoga** [comment]
> It would be also cool if one could do reverse text-object search in some cases like in vim, 

Good catch. Thank you for reporting the difference in the detailed behavior of the text object. That seems to be an oversight. I fixed the behavior in commit 5f9a44ec. Could you update ble.sh and check the behavior?

**Comment by Darukutsu** [comment]
Example 1. works now, but it is very specific. Example 2. still doesn't work.

`vi'` doesn't select `bar`
```
echo 'foo' 'bar' fff
                   ^
```

**Comment by akinomyoga** [comment]
> `vi'` doesn't select `bar`
> 
> ```
> echo 'foo' 'bar' fff
>                    ^
> ```

As far as I test it in Vim, that seems to be the behavior of Vim. I've tested it in Vim 9.0.


> also doing something like `vi)`

Actually, the text objects for `b()B{}<>[]` and `tsp` in xmap are not implemented. That is in [a ToDo list](https://github.com/akinomyoga/ble.sh/blob/5f9a44ec3364e238fd34db9ab706ce3868e5d2fb/note.txt#L6591).

**Comment by Darukutsu** [comment]
> As far as I test it in Vim, that seems to be the behavior of Vim. I've tested it in Vim 9.0.

Ah you right. I didn't know this isn't even possible in neovim by default. I have few plugins installed and didn't realize one of them provides this functionality. Could be feature request for future.

**Comment by akinomyoga** [comment]
In commit 7d80167c, I implemented the text-object behavior for brackets in xmap. Could you check it?

**Comment by Darukutsu** [comment]
Nice, xmap works as should now.
omap don't behave same as xmap with bracket types.

Also doing something like `di'u` 
```
//di'
echo 'foo'

//u
echo 'fo''
```

**Comment by akinomyoga** [comment]
> Nice, xmap works as should now. omap don't behave same as xmap with bracket types.

Ah, I thought I properly implemented it for omap, but it seems that wasn't the case. The related code was first introduced in 441ed955 (2017-09-13) which seems to be a quick support, and the logic hasn't been updated since then. Now, I investigated Vim's behavior also for omap and implemented the behavior in ble.sh in commit d1a1d538.

> Also doing something like `di'u`

Thank you for the report. This is fixed in commit c920ea65. This was a terrible bug. It is a big mystery that it appeared to work for most cases with that broken code.

Could you check them?

**Comment by Darukutsu** [comment]
Ok, everything seems to work now as should. Thank you for implementing it that fast.

**Comment by akinomyoga** [comment]
Thank you!
