### ISSUE TITLE
Prompt with vi-mode strings micalculating length

### ISSUE THREAD

**Issue by tigger04** [akinomyoga/ble.sh#60]
**ble version**: 0.4.0-devel2+f7dc477
**Bash version**: 5.0.18(1)-release, x86_64-apple-darwin19.5.0

The character width of my bash prompt appears to be miscalculated, resulting in unpredictable behaviour both for the prompt and the shell input.

I have made a video to demonstrate what I  mean:

https://www.youtube.com/watch?v=JFfKkFMK484&t=140s

This is similar to what you sometiems see in regular bash where e.g. ANSI colour codes have been used but not escaped properly for reeadline.

I should point out that I am setting my prompt in an unusual way. I found the custom indicators for command and insert mode (for vi-mode readline) to be quite limiting, so I have a prompt set like so, within a 'prompt_command' function":

```bash
  __prompt_command() {
      local _exit="$?"             # This needs to be first
      local _logo

      local _last_command="$(fc -l -1)"

      if [ $_exit -ne 0 ] && [[ "$_exit_notified_for" != "${_last_command}" ]]; then
          _logo="🔴"
          _exit_notified_for="${_last_command}"
      fi

      bind "set vi-ins-mode-string \"\1\e[6 q\2${_logo}${ansi[blue]}$(abbreviate_path "$PWD")${ansi[yellow]}→${ansi[yellow]}\""
      bind "set vi-cmd-mode-string \"\1\e[2 q\2${_logo}${ansi[blue]}$(abbreviate_path "$PWD")${ansi[blue]}:${ansi[yellow]}\""
      
      PS1=" "
      PS2="... "
  }
```

This lets you do quite a few additional things such as change the colour of the prompt depending on mode etc. Perhaps I no longer need this with the ble.sh indicators, but I thought this was wroth raising as something is going wrong with the custom indicators here in an upgrade from vanilla scenario.

I can attach the rest of my .bashrc if you think that might be useful.

You'll also note in the video a couple of odd errors I get on ble.sh launch, differing in the messaging between whether I have just sourced ble.sh or followed the full instructions to incorporate in to .bashrc

**Comment by tigger04** [comment]
My bash version seems to have got cut out of the original post - **Bash version**: 5.0.18(1)-release, x86_64-apple-darwin19.5.0

**Comment by akinomyoga** [comment]
Thank you for the report! I made two changes which I think should solve the behavior.

- f6fc7ff I fixed a problem that the mode strings are not shown when `ble.sh` is in auto-complete mode or some other sub-modes.
- 1954a1e I also changed to redraw the prompts in the partial update of the command line if necessary.

Could you check if the problem is solved with the latest version of `ble.sh`? `ble.sh` can be updated by the command `ble-update`.

**Comment by akinomyoga** [comment]
For the error messages related to `fzf` settings, could you please try the setting [here](https://github.com/akinomyoga/blesh-contrib#pencil-fzf-integration)?

**Comment by tigger04** [comment]
Yes indeed that seems to have fixed the prompt issue!
For the fzf errors, i tried both option 1 and option 2 in that link.

With option 1 (amend .fzf.bash) I still get:

```
-bash: _fzf_setup_completion: command not found
-bash: _fzf_setup_completion: command not found
-bash: _fzf_setup_completion: command not found

```
And with the second method (amend .blerc) I get:
```

ble.sh (bind): unsupported readline function 'fzf-file-widget'.
ble.sh (bind): unsupported readline function 'fzf-file-widget'.
ble.sh (bind): unsupported readline function 'fzf-file-widget'.
ble.sh (bind): unsupported readline function '__fzf_history__'.
ble.sh (bind): unsupported readline function '__fzf_history__'.
ble.sh (bind): unsupported readline function '__fzf_history__'.
```

**Comment by akinomyoga** [comment]
Thank you for checking the prompt issues!

> For the fzf errors, i tried both option 1 and option 2 in that link.

Hmm, I cannot reproduce. Which version of `fzf` do you use? If it is not the latest version, could you try to update `fzf`?

- The errors of `_fzf_setup_completion` are usually caused when a shell function `_fzf_setup_completion` is not defined. I guess these errors are generated at [`shells/completion.bash` @ junegunn/fzf](https://github.com/junegunn/fzf/blob/e2ae1b249cf2d5258b552cfd682c7c0911981e9b/shell/completion.bash#L368-L370), but the shell function `_fzf_setup_completion` is actually defined just above the lines.
- The `bind` errors are caused when one forgot to specify `-x` option. I guess these errors are generated in the lines [`shell/key-bindings.bash` @ junegunn/fzf](https://github.com/junegunn/fzf/blob/e2ae1b249cf2d5258b552cfd682c7c0911981e9b/shell/key-bindings.bash#L80-L88), but the option `-x` is correctly specified there.

Maybe it would help me to identify the problem if you could provide me the related section in your `fzf/shell/key-bindings.bash` and `fzf/shell/completion.bash`.

**Comment by tigger04** [comment]
fzf version 0.21 and on the back of this have just upgraded to 0.22 (no difference I'm afraid)

**completions.bash**
```

#     ____      ____
#    / __/___  / __/
#   / /_/_  / / /_
#  / __/ / /_/ __/
# /_/   /___/_/ completion.bash
#
# - $FZF_TMUX               (default: 0)
# - $FZF_TMUX_OPTS          (default: empty)
# - $FZF_COMPLETION_TRIGGER (default: '**')
# - $FZF_COMPLETION_OPTS    (default: empty)

if [[ $- =~ i ]]; then

# To use custom commands instead of find, override _fzf_compgen_{path,dir}
if ! declare -f _fzf_compgen_path > /dev/null; then
  _fzf_compgen_path() {
    echo "$1"
    command find -L "$1" \
      -name .git -prune -o -name .hg -prune -o -name .svn -prune -o \( -type d -o -type f -o -type l \) \
      -a -not -path "$1" -print 2> /dev/null | sed 's@^\./@@'
  }
fi

if ! declare -f _fzf_compgen_dir > /dev/null; then
  _fzf_compgen_dir() {
    command find -L "$1" \
      -name .git -prune -o -name .hg -prune -o -name .svn -prune -o -type d \
      -a -not -path "$1" -print 2> /dev/null | sed 's@^\./@@'
  }
fi

###########################################################

# To redraw line after fzf closes (printf '\e[5n')
bind '"\e[0n": redraw-current-line'

__fzf_comprun() {
  if [ "$(type -t _fzf_comprun 2>&1)" = function ]; then
    _fzf_comprun "$@"
  elif [ -n "$TMUX_PANE" ] && { [ "${FZF_TMUX:-0}" != 0 ] || [ -n "$FZF_TMUX_OPTS" ]; }; then
    shift
    fzf-tmux ${FZF_TMUX_OPTS:--d${FZF_TMUX_HEIGHT:-40%}} -- "$@"
  else
    shift
    fzf "$@"
  fi
}

__fzf_orig_completion_filter() {
  sed 's/^\(.*-F\) *\([^ ]*\).* \([^ ]*\)$/export _fzf_orig_completion_\3="\1 %s \3 #\2"; [[ "\1" = *" -o nospace "* ]] \&\& [[ ! "$__fzf_nospace_commands" = *" \3 "* ]] \&\& __fzf_nospace_commands="$__fzf_nospace_commands \3 ";/' |
  awk -F= '{OFS = FS} {gsub(/[^A-Za-z0-9_= ;]/, "_", $1);}1'
}

_fzf_opts_completion() {
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="
    -x --extended
    -e --exact
    --algo
    -i +i
    -n --nth
    --with-nth
    -d --delimiter
    +s --no-sort
    --tac
    --tiebreak
    -m --multi
    --no-mouse
    --bind
    --cycle
    --no-hscroll
    --jump-labels
    --height
    --literal
    --reverse
    --margin
    --inline-info
    --prompt
    --pointer
    --marker
    --header
    --header-lines
    --ansi
    --tabstop
    --color
    --no-bold
    --history
    --history-size
    --preview
    --preview-window
    -q --query
    -1 --select-1
    -0 --exit-0
    -f --filter
    --print-query
    --expect
    --sync"

  case "${prev}" in
  --tiebreak)
    COMPREPLY=( $(compgen -W "length begin end index" -- "$cur") )
    return 0
    ;;
  --color)
    COMPREPLY=( $(compgen -W "dark light 16 bw" -- "$cur") )
    return 0
    ;;
  --history)
    COMPREPLY=()
    return 0
    ;;
  esac

  if [[ "$cur" =~ ^-|\+ ]]; then
    COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
    return 0
  fi

  return 0
}

_fzf_handle_dynamic_completion() {
  local cmd orig_var orig ret orig_cmd orig_complete
  cmd="$1"
  shift
  orig_cmd="$1"
  orig_var="_fzf_orig_completion_$cmd"
  orig="${!orig_var##*#}"
  if [ -n "$orig" ] && type "$orig" > /dev/null 2>&1; then
    $orig "$@"
  elif [ -n "$_fzf_completion_loader" ]; then
    orig_complete=$(complete -p "$orig_cmd" 2> /dev/null)
    _completion_loader "$@"
    ret=$?
    # _completion_loader may not have updated completion for the command
    if [ "$(complete -p "$orig_cmd" 2> /dev/null)" != "$orig_complete" ]; then
      eval "$(complete | command grep " -F.* $orig_cmd$" | __fzf_orig_completion_filter)"
      if [[ "$__fzf_nospace_commands" = *" $orig_cmd "* ]]; then
        eval "${orig_complete/ -F / -o nospace -F }"
      else
        eval "$orig_complete"
      fi
    fi
    return $ret
  fi
}

__fzf_generic_path_completion() {
  local cur base dir leftover matches trigger cmd
  cmd="${COMP_WORDS[0]//[^A-Za-z0-9_=]/_}"
  COMPREPLY=()
  trigger=${FZF_COMPLETION_TRIGGER-'**'}
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "$cur" == *"$trigger" ]]; then
    base=${cur:0:${#cur}-${#trigger}}
    eval "base=$base"

    [[ $base = *"/"* ]] && dir="$base"
    while true; do
      if [ -z "$dir" ] || [ -d "$dir" ]; then
        leftover=${base/#"$dir"}
        leftover=${leftover/#\/}
        [ -z "$dir" ] && dir='.'
        [ "$dir" != "/" ] && dir="${dir/%\//}"
        matches=$(eval "$1 $(printf %q "$dir")" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS $2" __fzf_comprun "$4" -q "$leftover" | while read -r item; do
          printf "%q$3 " "$item"
        done)
        matches=${matches% }
        [[ -z "$3" ]] && [[ "$__fzf_nospace_commands" = *" ${COMP_WORDS[0]} "* ]] && matches="$matches "
        if [ -n "$matches" ]; then
          COMPREPLY=( "$matches" )
        else
          COMPREPLY=( "$cur" )
        fi
        printf '\e[5n'
        return 0
      fi
      dir=$(dirname "$dir")
      [[ "$dir" =~ /$ ]] || dir="$dir"/
    done
  else
    shift
    shift
    shift
    _fzf_handle_dynamic_completion "$cmd" "$@"
  fi
}

_fzf_complete() {
  # Split arguments around --
  local args rest str_arg i sep
  args=("$@")
  sep=
  for i in "${!args[@]}"; do
    if [[ "${args[$i]}" = -- ]]; then
      sep=$i
      break
    fi
  done
  if [[ -n "$sep" ]]; then
    str_arg=
    rest=("${args[@]:$((sep + 1)):${#args[@]}}")
    args=("${args[@]:0:$sep}")
  else
    str_arg=$1
    args=()
    shift
    rest=("$@")
  fi

  local cur selected trigger cmd post
  post="$(caller 0 | awk '{print $2}')_post"
  type -t "$post" > /dev/null 2>&1 || post=cat

  cmd="${COMP_WORDS[0]//[^A-Za-z0-9_=]/_}"
  trigger=${FZF_COMPLETION_TRIGGER-'**'}
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "$cur" == *"$trigger" ]]; then
    cur=${cur:0:${#cur}-${#trigger}}

    selected=$(FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS $str_arg" __fzf_comprun "${rest[0]}" "${args[@]}" -q "$cur" | $post | tr '\n' ' ')
    selected=${selected% } # Strip trailing space not to repeat "-o nospace"
    if [ -n "$selected" ]; then
      COMPREPLY=("$selected")
    else
      COMPREPLY=("$cur")
    fi
    printf '\e[5n'
    return 0
  else
    _fzf_handle_dynamic_completion "$cmd" "${rest[@]}"
  fi
}

_fzf_path_completion() {
  __fzf_generic_path_completion _fzf_compgen_path "-m" "" "$@"
}

# Deprecated. No file only completion.
_fzf_file_completion() {
  _fzf_path_completion "$@"
}

_fzf_dir_completion() {
  __fzf_generic_path_completion _fzf_compgen_dir "" "/" "$@"
}

_fzf_complete_kill() {
  local trigger=${FZF_COMPLETION_TRIGGER-'**'}
  local cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ -z "$cur" ]]; then
    COMP_WORDS[$COMP_CWORD]=$trigger
  elif [[ "$cur" != *"$trigger" ]]; then
    return 1
  fi

  _fzf_proc_completion "$@"
}

_fzf_proc_completion() {
  _fzf_complete -m --preview 'echo {}' --preview-window down:3:wrap --min-height 15 -- "$@" < <(
    command ps -ef | sed 1d
  )
}

_fzf_proc_completion_post() {
  awk '{print $2}'
}

_fzf_host_completion() {
  _fzf_complete +m -- "$@" < <(
    cat <(cat ~/.ssh/config ~/.ssh/config.d/* /etc/ssh/ssh_config 2> /dev/null | command grep -i '^\s*host\(name\)\? ' | awk '{for (i = 2; i <= NF; i++) print $1 " " $i}' | command grep -v '[*?]') \
        <(command grep -oE '^[[a-z0-9.,:-]+' ~/.ssh/known_hosts | tr ',' '\n' | tr -d '[' | awk '{ print $1 " " $1 }') \
        <(command grep -v '^\s*\(#\|$\)' /etc/hosts | command grep -Fv '0.0.0.0') |
        awk '{if (length($2) > 0) {print $2}}' | sort -u
  )
}

_fzf_var_completion() {
  _fzf_complete -m -- "$@" < <(
    declare -xp | sed 's/=.*//' | sed 's/.* //'
  )
}

_fzf_alias_completion() {
  _fzf_complete -m -- "$@" < <(
    alias | sed 's/=.*//' | sed 's/.* //'
  )
}

# fzf options
complete -o default -F _fzf_opts_completion fzf

d_cmds="${FZF_COMPLETION_DIR_COMMANDS:-cd pushd rmdir}"
a_cmds="
  awk cat diff diff3
  emacs emacsclient ex file ftp g++ gcc gvim head hg java
  javac ld less more mvim nvim patch perl python ruby
  sed sftp sort source tail tee uniq vi view vim wc xdg-open
  basename bunzip2 bzip2 chmod chown curl cp dirname du
  find git grep gunzip gzip hg jar
  ln ls mv open rm rsync scp
  svn tar unzip zip"

# Preserve existing completion
eval "$(complete |
  sed -E '/-F/!d; / _fzf/d; '"/ ($(echo $d_cmds $a_cmds | sed 's/ /|/g; s/+/\\+/g'))$/"'!d' |
  __fzf_orig_completion_filter)"

if type _completion_loader > /dev/null 2>&1; then
  _fzf_completion_loader=1
fi

__fzf_defc() {
  local cmd func opts orig_var orig def
  cmd="$1"
  func="$2"
  opts="$3"
  orig_var="_fzf_orig_completion_${cmd//[^A-Za-z0-9_]/_}"
  orig="${!orig_var}"
  if [ -n "$orig" ]; then
    printf -v def "$orig" "$func"
    eval "$def"
  else
    complete -F "$func" $opts "$cmd"
  fi
}

# Anything
for cmd in $a_cmds; do
  __fzf_defc "$cmd" _fzf_path_completion "-o default -o bashdefault"
done

# Directory
for cmd in $d_cmds; do
  __fzf_defc "$cmd" _fzf_dir_completion "-o nospace -o dirnames"
done

# Kill completion (supports empty completion trigger)
complete -F _fzf_complete_kill -o default -o bashdefault kill

unset cmd d_cmds a_cmds

_fzf_setup_completion() {
  local kind fn cmd
  kind=$1
  fn=_fzf_${1}_completion
  if [[ $# -lt 2 ]] || ! type -t "$fn" > /dev/null; then
    echo "usage: ${FUNCNAME[0]} path|dir|var|alias|host|proc COMMANDS..."
    return 1
  fi
  shift
  eval "$(complete -p "$@" 2> /dev/null | grep -v "$fn" | __fzf_orig_completion_filter)"
  for cmd in "$@"; do
    case "$kind" in
      dir)   __fzf_defc "$cmd" "$fn" "-o nospace -o dirnames" ;;
      var)   __fzf_defc "$cmd" "$fn" "-o default -o nospace -v" ;;
      alias) __fzf_defc "$cmd" "$fn" "-a" ;;
      *)     __fzf_defc "$cmd" "$fn" "-o default -o bashdefault" ;;
    esac
  done
}

# Environment variables / Aliases / Hosts
_fzf_setup_completion 'var'   export unset
_fzf_setup_completion 'alias' unalias
_fzf_setup_completion 'host'  ssh telnet

fi

```


**key-bindings.bash**
```
#     ____      ____
#    / __/___  / __/
#   / /_/_  / / /_
#  / __/ / /_/ __/
# /_/   /___/_/ key-bindings.bash
#
# - $FZF_TMUX_OPTS
# - $FZF_CTRL_T_COMMAND
# - $FZF_CTRL_T_OPTS
# - $FZF_CTRL_R_OPTS
# - $FZF_ALT_C_COMMAND
# - $FZF_ALT_C_OPTS

# Key bindings
# ------------
__fzf_select__() {
  local cmd="${FZF_CTRL_T_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null | cut -b3-"}"
  eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" $(__fzfcmd) -m "$@" | while read -r item; do
    printf '%q ' "$item"
  done
  echo
}

if [[ $- =~ i ]]; then

__fzfcmd() {
  [ -n "$TMUX_PANE" ] && { [ "${FZF_TMUX:-0}" != 0 ] || [ -n "$FZF_TMUX_OPTS" ]; } &&
    echo "fzf-tmux ${FZF_TMUX_OPTS:--d${FZF_TMUX_HEIGHT:-40%}} -- " || echo "fzf"
}

fzf-file-widget() {
  local selected="$(__fzf_select__)"
  READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
  READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
}

__fzf_cd__() {
  local cmd dir
  cmd="${FZF_ALT_C_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type d -print 2> /dev/null | cut -b3-"}"
  dir=$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" $(__fzfcmd) +m) && printf 'cd %q' "$dir"
}

__fzf_history__() {
  local output
  output=$(
    builtin fc -lnr -2147483648 |
      last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |
      FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m --read0" $(__fzfcmd) --query "$READLINE_LINE"
  ) || return
  READLINE_LINE=${output#*$'\t'}
  if [ -z "$READLINE_POINT" ]; then
    echo "$READLINE_LINE"
  else
    READLINE_POINT=0x7fffffff
  fi
}

# Required to refresh the prompt after fzf
bind -m emacs-standard '"\er": redraw-current-line'

bind -m vi-command '"\C-z": emacs-editing-mode'
bind -m vi-insert '"\C-z": emacs-editing-mode'
bind -m emacs-standard '"\C-z": vi-editing-mode'

if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
  # CTRL-T - Paste the selected file path into the command line
  bind -m emacs-standard '"\C-t": " \C-b\C-k \C-u`__fzf_select__`\e\C-e\er\C-a\C-y\C-h\C-e\e \C-y\ey\C-x\C-x\C-f"'
  bind -m vi-command '"\C-t": "\C-z\C-t\C-z"'
  bind -m vi-insert '"\C-t": "\C-z\C-t\C-z"'

  # CTRL-R - Paste the selected command from history into the command line
  bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u"$(__fzf_history__)"\e\C-e\er"'
  bind -m vi-command '"\C-r": "\C-z\C-r\C-z"'
  bind -m vi-insert '"\C-r": "\C-z\C-r\C-z"'
else
  # CTRL-T - Paste the selected file path into the command line
  bind -m emacs-standard -x '"\C-t": fzf-file-widget'
  bind -m vi-command -x '"\C-t": fzf-file-widget'
  bind -m vi-insert -x '"\C-t": fzf-file-widget'

  # CTRL-R - Paste the selected command from history into the command line
  bind -m emacs-standard -x '"\C-r": __fzf_history__'
  bind -m vi-command -x '"\C-r": __fzf_history__'
  bind -m vi-insert -x '"\C-r": __fzf_history__'
fi

# ALT-C - cd into the selected directory
bind -m emacs-standard '"\ec": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"\ec": "\C-z\ec\C-z"'
bind -m vi-insert '"\ec": "\C-z\ec\C-z"'

fi

```

**Comment by akinomyoga** [comment]
Thank you for checking and providing the `fzf` configuration. OK, there seems to be no problem in `completion.bash` and `key-bindings.bash`. I also tried different Bash versions and different loading order of `fzf` settings, but I still cannot reproduce the problem. I think it will take several more steps to pin down the problems.

### Error message in option 1

> With option 1 (amend .fzf.bash) I still get:
> 
> ```
> -bash: _fzf_setup_completion: command not found
> -bash: _fzf_setup_completion: command not found
> -bash: _fzf_setup_completion: command not found
> ```

To confirm that the above messages (in option 1) are produced in `fzf/shell/completion.bash`, can you edit `fzf/shell/completion.bash` as follows and see the messages? (Please back up your original `fzf/shell/completion.bash` before the edit.)

```diff
diff --git a/shell/completion.bash b/shell/completion.bash
index 3f6161d..d59da09 100644
--- a/shell/completion.bash
+++ b/shell/completion.bash
@@ -344,6 +344,7 @@ complete -F _fzf_complete_kill -o default -o bashdefault kill

 unset cmd d_cmds a_cmds

+echo DEBUG A >/dev/tty
 _fzf_setup_completion() {
   local kind fn cmd
   kind=$1
@@ -365,8 +366,11 @@ _fzf_setup_completion() {
 }

 # Environment variables / Aliases / Hosts
+echo DEBUG B >/dev/tty
+type -t _fzf_setup_completion >/dev/tty
 _fzf_setup_completion 'var'   export unset
 _fzf_setup_completion 'alias' unalias
 _fzf_setup_completion 'host'  ssh telnet
+echo DEBUG C >/dev/tty

 fi
```

### Error message in option 2

> And with the second method (amend .blerc) I get:
> 
> ```
> ble.sh (bind): unsupported readline function 'fzf-file-widget'.
> ble.sh (bind): unsupported readline function 'fzf-file-widget'.
> ble.sh (bind): unsupported readline function 'fzf-file-widget'.
> ble.sh (bind): unsupported readline function '__fzf_history__'.
> ble.sh (bind): unsupported readline function '__fzf_history__'.
> ble.sh (bind): unsupported readline function '__fzf_history__'.
> ```

Similarly, can you try the following modification to `fzf/shell/key-bindings.bash` for option 2 and see what the messages are?

```diff
diff --git a/shell/key-bindings.bash b/shell/key-bindings.bash
index e157b07..a05cb73 100644
--- a/shell/key-bindings.bash
+++ b/shell/key-bindings.bash
@@ -77,6 +77,8 @@ if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
   bind -m vi-command '"\C-r": "\C-z\C-r\C-z"'
   bind -m vi-insert '"\C-r": "\C-z\C-r\C-z"'
 else
+  echo DEBUG X >/dev/tty
+  type -t bind >/dev/tty
   # CTRL-T - Paste the selected file path into the command line
   bind -m emacs-standard -x '"\C-t": fzf-file-widget'
   bind -m vi-command -x '"\C-t": fzf-file-widget'
@@ -86,6 +88,7 @@ else
   bind -m emacs-standard -x '"\C-r": __fzf_history__'
   bind -m vi-command -x '"\C-r": __fzf_history__'
   bind -m vi-insert -x '"\C-r": __fzf_history__'
+  echo DEBUG Y >/dev/tty
 fi

 # ALT-C - cd into the selected directory
```

**Comment by tigger04** [comment]
In terms of reproducing the issue, I wonder could it be the way in which I"m invoking fzf from my .bashrc? Ii've included it here in case that helps - will try the above modifications shorlty

```
#!/usr/local/bin/bash

if [[ $- == *i* && -f ~/.ble_enabled ]]; then
  
  ## ^^ I have customized this condition ^^

  _ble_is_enabled=true
  
  ## ^^ and this obviously ^^

  source ~/code/ble.sh/out/ble.sh noattach

    # Add this code after "source ble.sh ..."

    function debug/complete-load-hook {
    filename_debug_log=~/bin/scratch/ble-debug
    function timestamp-args.advice {
        echo "$EPOCHREALTIME ${ADVICE_WORDS[*]}" >> "$filename_debug_log"
    }
    ble/function#advice \
        before ble-decode/.hook \
        timestamp-args.advice

    function timestamp-wrap.advice {
        echo "$EPOCHREALTIME ${ADVICE_WORDS[0]} start" >> "$filename_debug_log"
        ble/function#advice/do
        echo "$EPOCHREALTIME ${ADVICE_WORDS[0]} end" >> "$filename_debug_log"
    }
    ble/function#advice \
        around ble/complete/progcomp/.compgen-helper-prog \
        timestamp-wrap.advice
    ble/function#advice \
        around ble/complete/progcomp/.compgen-helper-func \
        timestamp-wrap.advice
    }
    blehook/eval-after-load complete debug/complete-load-hook

  # settings for ble.sh...
else
  unset _ble_is_enabled
fi

# your bashrc settings come here...

#determine OS for later use (in bashrc and it's children sourced files, and in life)
_os=$(uname)
export _os

. ~/.aliases.sh
. ~/bin/helper-funcs.sh

# linux .
# pbcopy='xclip -selection clipboard'
# pbpaste='xclip -selection clipboard -p'

# PS1 / colors see https://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-ps1-prompt

shopt -s extglob
shopt -s nullglob
shopt -s nocasematch
shopt -s dotglob
shopt -s autocd
shopt -s cdspell
[ $_ble_is_enabled ] || complete -d cd
CDPATH='.:~:~/code:~/bin'

# there was some useful bash stuff here https://gist.github.com/gre11rynicholas/1812027

#this *might* bkle useful for bash (check) but doesn't seem to do anything in zsh
set expand-tilde on

#this would be useful for bash but doesn't work in zsh
set visible-stats on

#mod for fzf-obc
# export PATH=/usr/local/opt/gnu-sed/bin:/usr/local/opt/coreutils/gnubin:/usr/local/opt/findutils/gnubin:$PATH:~/bin:~/.vimpkg/bin
export PATH=$PATH:~/bin:~/.vimpkg/bin

# weather_icon=$(curl -sm2 'http://wttr.in/LDublin?format=%m')
(
  {  
    sleep 1
    curl -sm2 'http://wttr.in/Dublin?format=%l:+%c+%f' > ~/.weather-today
  } &
) # sep process stops us having to look at the 'Done' in the terminal when the proc finishes

__prompt_command() {
    local _exit="$?"             # This needs to be first
    local _logo

    local _last_command="$(fc -l -1)"

    if [ $_exit -ne 0 ] && [[ "$_exit_notified_for" != "${_last_command}" ]]; then
        _logo="🔴"
        _exit_notified_for="${_last_command}"
    # else
    #     _logo="🐹"
    fi

    # if [ $_ble_is_enabled ]; then
    #     PS1="${ansi[green]}\w${ansi[yellow]}\$${ansi[off]} "
    #     PS2="${ansi[green]} ... "
    # else
        bind "set vi-ins-mode-string \"\1\e[6 q\2${_logo}${ansi[blue]}$(abbreviate_path "$PWD")${ansi[yellow]}→${ansi[yellow]}\""
        bind "set vi-cmd-mode-string \"\1\e[2 q\2${_logo}${ansi[blue]}$(abbreviate_path "$PWD")${ansi[blue]}:${ansi[yellow]}\""
        
        PS1=" "
        PS2="... "
    # fi
}


#useful stuff to add
shopt -s histappend
PROMPT_COMMAND_ORIGINAL="$PROMPT_COMMAND"
PROMPT_COMMAND="__prompt_command;history -a;$PROMPT_COMMAND_ORIGINAL"

#bind '"\e[A":history-search-backward'
#bind '"\e[B":history-search-forward'
# bind "\C-p":clear-screen
# bind -x '"\e[":"pushd .."'
# bind -x '"\e]":"popd"'

_cache_issues () {
    (
        if [ $# -ge 1 ]; then
            cd "$1" || return 1
        else
            cd "$HOME" || return 1
        fi
        
        {
            sleep 1
            ghi list -g -L next | \grep -v '# Global, open issues that you can see, labeled next' > .issues-cache
            # echo updated cache
        } &
        # popd >/dev/null 2>&1 || return 1
        # dont need this we're in a subshell
    )
}

# _cache_issues "$HOME/bin" || echo xxx bin
# _cache_issues "$HOME/dotfiles" || echo xxx dotfiles

_cache_issues || echo "problem with _cache_issues"

# --> moving all this below 
# } | grep -v "open issues that you can"

# export VISUAL="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
export VISUAL="$HOME/bin/v -w"
#export EDITOR="$VISUAL"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
# usage: _fzf_setup_completion path|dir|var|alias|host COMMANDS...
_fzf_setup_completion path ag git kubectl cp mv
_fzf_setup_completion dir tree
_fzf_setup_completion var for which if 
# FZF_COMPLETION_TRIGGER=''

if ! [ $_ble_is_enabled ]; then
    complete -F _fzf_path_completion -o default -o bashdefault cd
    complete -F _fzf_path_completion -o default -o bashdefault l
    complete -F _fzf_path_completion -o default -o bashdefault ls
    complete -F _fzf_path_completion -o default -o bashdefault v
    complete -F _fzf_path_completion -o default -o bashdefault cat
    complete -F _fzf_path_completion -o default -o bashdefault less
    complete -F _fzf_path_completion -o default -o bashdefault vimpager
    complete -F _fzf_path_completion -o default -o bashdefault vi

    _fzf_complete_ssh_notrigger() {
        FZF_COMPLETION_TRIGGER='' _fzf_host_completion
    }

    # complete -o bashdefault -o default -F _fzf_complete_ssh_notrigger cd
    # complete -o bashdefault -o default -F _fzf_complete_ssh_notrigger l
fi

export HISTTIMEFORMAT="%F %H:%M "
export HISTFILESIZE=10000
export HISTSIZE=10000
export HISTCONTROL=ignorespace
shopt -s cmdhist
export HISTFILE=~/.bash_history

export CHEAT_USE_FZF=true

# [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# This one's for fzf-obc
# source /Users/tadhg.obrien/code/fzf-obc/bin/fzf-obc.bash/

# this output gives an important function in highlighting if there's a problem
# with my bash4+ dependant printf function for date which is relied on down the 
# line in scripts - hence on its own line
printf '%s[' "${ansi[iwhite]}${ansi[bold]}"
# date -r ~/bin/.issues-cache "+%F %H:%M"
_report_date=$(date -r ~/.issues-cache "+%F %H:%M")
printf '%s]' "$_report_date"
maybe_weather_string="$( cd ~ && fd .weather-today -g -d1 -H --changed-within 6hours -x cat {} | tr -d '\n' )"
printf "%60.60s%s\n" "$maybe_weather_string" "${ansi[off]}"

vimcat "$HOME/.issues-cache"
# vimcat "$HOME/bin/.issues-cache"
# vimcat "$HOME/dotfiles/.issues-cache"

echo -ne "${ansi[cyan]}"
if [[ "$_os" == "Darwin" ]]; then
    # mac only stuff goes here
    echo -e "Hello Mac passenger! 🌍"
    # sudo pmset -c displaysleep 999

elif [[ "$_os" == "Linux" ]]; then
    # linux only stuff goes here
    echo -e "Hello Linux cosmonaut! 🚀"
    gsettings set org.gnome.desktop.interface enable-animations false
else
    # alpine? should report linux also though?
    echo -e "*** interesting, have not seen $_os before 🤷‍♂️ ***"
fi
echo -ne "${ansi[off]}"

# [[ -s "/etc/profile.d/grc.bashrc" ]] && source /etc/profile.d/grc.bashrc


# Add this line at the end of .bashrc:
$_ble_is_enabled && ((_ble_bash)) && ble-attach && complete -r

## ^^ added complete -r here as well ^^

#this must be last line
[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh

```

**Comment by tigger04** [comment]
You'll see from the code I have disabled those completions if ble.sh is enabled, so this is not an urgent issue for me. But happy to get to the bottom of it in case it helps other users with a similar setup when migrating to ble.sh

**Comment by akinomyoga** [comment]
> In terms of reproducing the issue, I wonder could it be the way in which I"m invoking fzf from my .bashrc? Ii've included it here in case that helps

Thank you! It's a big help!

### Error messages `-bash: _fzf_setup_completion: command not found`

I found the cause. Actually, in [the setting Option 1](https://github.com/akinomyoga/blesh-contrib#option-1-setup-in-fzfbash), the load of fzf settings are asynchronous so that `key-bindings.bash` and `completion.bash` are sourced after the shell becomes idle. Therefore `completion.bash` has not yet been sourced just after `source ~/.fzf.bash`. This causes the errors of `-bash: _fzf_setup_completion: command not found` in the following part of `.bashrc`.

> ```bash
> [ -f ~/.fzf.bash ] && source ~/.fzf.bash
> # usage: _fzf_setup_completion path|dir|var|alias|host COMMANDS...
> _fzf_setup_completion path ag git kubectl cp mv
> _fzf_setup_completion dir tree
> _fzf_setup_completion var for which if 
> # FZF_COMPLETION_TRIGGER=''
> ```

To solve this, you can synchronously load `completion.bash` by modifying `.fzf.bash` of Option 1 as follows (drop `-d` option):

```diff
 # Auto-completion
 # ---------------
 if [[ $BLE_VERSION ]]; then
-  ble-import -d contrib/fzf-completion
+  ble-import contrib/fzf-completion
 else
```

>  - will try the above modifications shorlty

Now you don't have to check the messages for "Error message in option 1".

### Error messages of `ble.sh (bind): unsupported readline function ...`

For these error messages, I still don't get the reason.

> But happy to get to the bottom of it in case it helps other users with a similar setup when migrating to ble.sh

Thank you! If you could continue to help me, it would be useful if you could collect the message with the settings in https://github.com/akinomyoga/ble.sh/issues/60#issuecomment-669464399 - "Error messages in option 2"

**Comment by akinomyoga** [comment]
Unrelated to the debugging, but I noticed the following points in your `bashrc`.

The following settings are readline settings so should be specified in arguments of `bind`:

```diff
diff --git a/bashrc b/bashrc
index cd79e84..2bbf1fd 100644
--- a/bashrc
+++ b/bashrc
@@ -67,10 +67,10 @@ CDPATH='.:~:~/code:~/bin'
 # there was some useful bash stuff here https://gist.github.com/gre11rynicholas/1812027

 #this *might* bkle useful for bash (check) but doesn't seem to do anything in zsh
-set expand-tilde on
+bind 'set expand-tilde on'

 #this would be useful for bash but doesn't work in zsh
-set visible-stats on
+bind 'set visible-stats on'

 #mod for fzf-obc
 # export PATH=/usr/local/opt/gnu-sed/bin:/usr/local/opt/coreutils/gnubin:/usr/local/opt/findutils/gnubin:$PATH:~/bin:~/.vimpkg/bin
```

I think `_fzf_setup_completion` can be called conditionally when the fzf is loaded by `.fzf.bash`.

```diff
diff --git a/bashrc b/bashrc
index 2bbf1fd..e567d88 100644
--- a/bashrc
+++ b/bashrc
@@ -151,12 +151,14 @@ _cache_issues || echo "problem with _cache_issues"
 export VISUAL="$HOME/bin/v -w"
 #export EDITOR="$VISUAL"

-[ -f ~/.fzf.bash ] && source ~/.fzf.bash
-# usage: _fzf_setup_completion path|dir|var|alias|host COMMANDS...
-_fzf_setup_completion path ag git kubectl cp mv
-_fzf_setup_completion dir tree
-_fzf_setup_completion var for which if
-# FZF_COMPLETION_TRIGGER=''
+if [ -f ~/.fzf.bash ]; then
+  source ~/.fzf.bash
+  # usage: _fzf_setup_completion path|dir|var|alias|host COMMANDS...
+  _fzf_setup_completion path ag git kubectl cp mv
+  _fzf_setup_completion dir tree
+  _fzf_setup_completion var for which if
+  # FZF_COMPLETION_TRIGGER=''
+fi

 if ! [ $_ble_is_enabled ]; then
     complete -F _fzf_path_completion -o default -o bashdefault cd
```

**Comment by tigger04** [comment]
Sorry I have not got back to you sooner. I had put in your debug statements but got sidetracked with a load of work before I got to send the results. My 'landing page' as such always had a bit of of clutter wtiht github issues displayed in there, but those original errors sort of faded in to the background for a few days. I picked this up again today to look at implementing your change to fix those errors ... and I'm scratching my head here, because they are not there.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/43514058/89711598-3157c400-d983-11ea-9830-3b2cdaefd600.png">

I'll let you know if  I can figure out what might have changed. I don't suppose ble.sh auto-updates itself?

**Comment by akinomyoga** [comment]
Thank you for the information.

> but those original errors sort of faded in to the background for a few days.

This kind of *heisenbugs* sometimes occurs, so don't worry.

> I'll let you know if I can figure out what might have changed. I don't suppose ble.sh auto-updates itself?

Thank you. `ble.sh` doesn't automatically update itself unless you explicitly run `ble-update`.

**Comment by tigger04** [comment]
You can disregard previous comment (deleted) - sorry i would not have deleted if i had seen your reply already come through. I had temporarily disabled ble.sh, hence the errors disappeared.

OK, I have made the change but still seeing those errors.
```
DEBUG A
DEBUG B
function
DEBUG C
DEBUG X
type -t bind
ble.sh (bind): unsupported readline function 'fzf-file-widget'.
ble.sh (bind): unsupported readline function 'fzf-file-widget'.
ble.sh (bind): unsupported readline function 'fzf-file-widget'.
ble.sh (bind): unsupported readline function '__fzf_history__'.
ble.sh (bind): unsupported readline function '__fzf_history__'.
ble.sh (bind): unsupported readline function '__fzf_history__'.
DEBUG Y
[2020-08-08 14:45]                                      Dublin: ⛅️  +18°C
  bin 53  bb_menu [next]
  bin 48  fix lnhome - dotfiles [next]
  bin 47  alt tools (exa etc) [next]
  bin 13  new note.sh todos [next]
Hello Mac passenger! 🌍
~/code/bin/scratch→ DEBUG A
DEBUG BRT --
function
DEBUG C
DEBUG X
type -t bind
DEBUG Y
cd
~→
-- INSERT --

```

**Comment by tigger04** [comment]
Looking at the change, it hasn't actually changed anything in the logic to move the loading from the && 'and' statement to within the if statement, except that those _fzf_setup_completion statements only get called now if .fzf.bash exists and has been sourced. Is this what you intended?

You mentioned something about async - did you read that as & async rather than && 'and' by any chance?

**Comment by akinomyoga** [comment]
> ```
> DEBUG A
> DEBUG B
> function
> DEBUG C
> DEBUG X
> type -t bind
> ble.sh (bind): unsupported readline function 'fzf-file-widget'.
> ble.sh (bind): unsupported readline function 'fzf-file-widget'.
> ble.sh (bind): unsupported readline function 'fzf-file-widget'.
> ble.sh (bind): unsupported readline function '__fzf_history__'.
> ble.sh (bind): unsupported readline function '__fzf_history__'.
> ble.sh (bind): unsupported readline function '__fzf_history__'.
> DEBUG Y
> ```

Thank you! Now I got confirmation that these errors are actually caused between `DEBUG X` and `DEBUG Y`. I still cannot reproduce the problem, but I'm going to think about the possible cause at my side.

> except that those _fzf_setup_completion statements only get called now if .fzf.bash exists and has been sourced.

Yes. This is what I intended. The function `_fzf_setup_completion` is only available after the source of `.fzf.bash`, so the original code will cause `-bash: _fzf_setup_completion: command not found` error when `.fzf.bash` doesn't exist (though I guess this is unrelated to the same error message with `ble.sh`).

> You mentioned something about async - did you read that as & async rather than && 'and' by any chance?

No. Sorry for the confusing explanation, but the comment on async loading and the comment on bashrc change are independent of each other. [Option 1 setting](https://github.com/akinomyoga/blesh-contrib#option-1-setup-in-fzfbash) loads `fzf` with `ble-import -d` where `-d` specifies that `fzf` shall be loaded asynchronously.

**Comment by akinomyoga** [comment]
Thank you!

855cacf Fixed for the messages `ble.sh (bind): unsupported readline function` (in Option 2).

For the messages `-bash: _fzf_setup_completion: command not found` (in Option 1), as I have already described, please edit `.fzf.bash` as follows:

```diff
 # Auto-completion
 # ---------------
 if [[ $BLE_VERSION ]]; then
-  ble-import -d contrib/fzf-completion
+  ble-import contrib/fzf-completion
 else
```

Can you check that the error messages are not present now with the latest version?

**Comment by tigger04** [comment]
It all looks good! thank you again for your help :)
Sorry I've been a bit slow getting back to you ... one of those weeks

**Comment by tigger04** [comment]
PS thanks for the tips on my .bashrc, I had b been meaning to get around to looking at why those 2 options never worked

**Comment by akinomyoga** [comment]
Thank you, too, for taking your time while you are busy. Your responses were quick enough.
