### ISSUE TITLE
transiet prompt oh my posh

### ISSUE THREAD

**Issue by y2w8** [akinomyoga/ble.sh#629]
```console
$ ble summary

GNU bash, version 5.2.37(1)-release (x86_64-redhat-linux-gnu) [Nobara Linux 42 (KDE Plasma Desktop Edition)]
ble.sh, version 0.4.0-devel4+8060b7ad (noarch) [git 2.50.1, GNU Make 4.4.1, GNU Awk 5.3.1, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.2, GNU MP 6.3.0)]
bash-completion, version 2.16.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
fzf completion, (hash:965bdb40dadd1a88d840c51304197e297b7af8a2, 20443 bytes) (noarch) (integration: off)
WARNING: fzf integration "integration/fzf-completion" is not activated.
starship, version 1.22.1 (rustc 1.86.0 (05f9846f8 2025-03-31) (Fedora 1.86.0-1.fc42), 2024-05-15 00:00:00 +00:00)
zoxide, version 0.9.4 (/usr/bin/zoxide) (integration: off)
locale: LANG=en_US.UTF-8 LC_ADDRESS=ar_SA.utf8 LC_IDENTIFICATION=ar_SA.utf8 LC_MEASUREMENT=ar_SA.utf8 LC_MONETARY=ar_SA.utf8 LC_NAME=ar_SA.utf8 LC_NUMERIC=ar_SA.utf8 LC_PAPER=ar_SA.utf8 LC_TELEPHONE=ar_SA.utf8 LC_TIME=ar_SA.utf8
terminal: TERM=xterm-256color wcwidth=15.0-west/16.0-2+ri, konsole:220380 (1;115;0)
options: +extglob +histappend -hostcomplete +inherit_errexit +login_shell

```

the problem the transiet prompt in oh my posh print twice when start new terminal
```console
~ 
~ 
>
```
because of ble-attach is after oh-my-posh init in .bashrc
```console
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PS1=""
export PROMPT_COMMAND=""
eval "$(oh-my-posh init bash --config /home/y2w8/.config/ohmyposh/mocha.omp.json)"
eval "$(zoxide init --cmd cd bash)"
export PATH=$PATH:/usr/lib64/qt6/bin
export QTWEBENGINE_DISABLE_SANDBOX=1
export QTWEBENGINE_USE_VULKAN=1
bleopt color_scheme=catppuccin_mocha

. "$HOME/.cargo/env"

[[ ! ${BLE_VERSION-} ]] || ble-attach
``` 
and when i tried to put oh-my-posh after ble-attach  it return to it didnt work (oh my posh)

**Comment by akinomyoga** [comment]
Sorry for the delay. I tried your settings, but the problem doesn't reproduce.

I also tried it in Konsole, but the problem doesn't reproduce.

I also created an OMP configuration file with a transient prompt referencing the documentation of Oh My Posh as follows, but the problem still doesn't reproduce:

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "transient_prompt": {
    "background": "transparent",
    "foreground": "#ffffff",
    "template": "{{ .Shell }}> "
  },
  "final_space": true,
  "version": 3,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#ffffff",
          "background": "#61AFEF",
          "properties": {
            "style": "folder"
          }
        }
      ]
    }
  ],
  "version": 2
}
```

> ```bash
> export PATH=$PATH:/usr/lib64/qt6/bin
> export QTWEBENGINE_DISABLE_SANDBOX=1
> export QTWEBENGINE_USE_VULKAN=1
> ```

Are these necessary to reproduce the problem? How should I set up these?

**Comment by akinomyoga** [comment]
> eval "$(oh-my-posh init bash --config /home/y2w8/.config/ohmyposh/mocha.omp.json)"

Could you provide the contents of `/home/y2w8/.config/ohmyposh/mocha.omp.json` (preferably the minimum configuration that reproduces the problem)?

**Comment by y2w8** [comment]
```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "palette": {
    "rosewater": "#F5E0DC",
    "flamingo": "#F2CDCD",
    "pink": "#F5C2E7",
    "mauve": "#CBA6F7",
    "red": "#F38BA8",
    "maroon": "#EBA0AC",
    "peach": "#FAB387",
    "yellow": "#F9E2AF",
    "green": "#A6E3A1",
    "teal": "#94E2D5",
    "sky": "#89DCEB",
    "sapphire": "#74C7EC",
    "blue": "#89B4FA",
    "lavender": "#B4BEFE",
    "text": "#CDD6F4",
    "subtext1": "#BAC2DE",
    "subtext0": "#A6ADC8",
    "overlay2": "#9399B2",
    "overlay1": "#7F849C",
    "overlay0": "#6C7086",
    "surface2": "#585B70",
    "surface1": "#45475A",
    "surface0": "#313244",
    "base": "#1E1E2E",
    "mantle": "#181825",
    "crust": "#11111B",
    "true": "p:green",
    "false": "p:red",
    "time": "p:overlay1",
    "os-fg": "p:base",
    "os-bg": "p:overlay1",
    "root-fg": "p:base",
    "root-bg": "p:yellow",
    "path": "p:yellow",
    "git": "p:lavender",
    "docker": "p:blue",
    "go": "p:mauve",
    "haskell": "p:mauve",
    "julia": "p:mauve",
    "lua": "p:mauve",
    "python": "p:mauve",
    "rust": "p:mauve",
    "react": "p:sapphire"
  },
  "transient_prompt": {
    "style": "plain",
    "foreground": "p:time",
    "template": "{{ now | date \"15:04:05\" }} {{ if gt .Code 0 }}<p:false>\u276f</>{{ else }}<p:true>\u276f</>{{ end }} ",
    "type": "text"
  },
  "secondary_prompt": {
    "style": "plain",
    "foreground": "p:rosewater",
    "template": "\u276f\u276f ",
    "type": "text"
  },
  "blocks": [
    {
      "alignment": "left",
      "type": "prompt",
      "newline": true,
      "segments": [
        {
          "foreground": "p:os",
          "style": "plain",
          "template": "{{.Icon}} ",
          "type": "os"
        },
        {
          "foreground": "p:rosewater",
          "style": "plain",
          "template": "{{ .Path }} ",
          "type": "path",
          "properties": {
            "folder_icon": "..\ue5fe..",
            "home_icon": "~",
            "style": "full"
          }
        },
        {
          "type": "docker",
          "style": "plain",
          "foreground": "p:docker",
          "template": "\uf308 {{ .Context }} "
        },
        {
          "type": "go",
          "style": "plain",
          "foreground": "p:go",
          "template": "\ue627 {{ if not .Error }}{{ .Full }}{{ end }} "
        },
        {
          "type": "haskell",
          "style": "plain",
          "foreground": "p:haskell",
          "template": "\ue61f {{ if not .Error }}{{ .Full }}{{ end }} "
        },
        {
          "type": "julia",
          "style": "plain",
          "foreground": "p:julia",
          "template": "\ue624 {{ if not .Error }}{{ .Full }}{{ end }} "
        },
        {
          "type": "lua",
          "style": "plain",
          "foreground": "p:lua",
          "template": "\ue620 {{ if not .Error }}{{ .Full }}{{ end }} "
        },
        {
          "type": "python",
          "style": "plain",
          "foreground": "p:python",
          "template": "\ue73c {{ if not .Error }}{{ if .Venv }}venv/{{ end }}{{ .Full }}{{ end }} ",
          "properties": {
            "display_default": false,
            "display_mode": "context"
          }
        },
        {
          "type": "react",
          "style": "plain",
          "foreground": "p:react",
          "template": " {{ if not .Error }}{{ .Full }}{{ end }} ",
          "properties": {
            "display_default": false,
            "display_mode": "context"
          }
        },
        {
          "type": "rust",
          "style": "plain",
          "foreground": "p:rust",
          "template": "\ue7a8 {{ if not .Error }}{{ .Full }}{{ end }} "
        },
        {
          "foreground": "p:lavender",
          "properties": {
            "branch_icon": "\ue725 ",
            "cherry_pick_icon": "\ue29b ",
            "commit_icon": "\uf417 ",
            "fetch_status": false,
            "fetch_upstream_icon": false,
            "merge_icon": "\ue727 ",
            "no_commits_icon": "\uf0c3 ",
            "rebase_icon": "\ue728 ",
            "revert_icon": "\uf0e2 ",
            "tag_icon": "\uf412 "
          },
          "template": "{{ .HEAD }} ",
          "style": "plain",
          "type": "git"
        }
      ]
    },
    {
      "alignment": "right",
      "type": "prompt",
      "segments": [
        {
          "type": "executiontime",
          "style": "plain",
          "foreground": "p:true",
          "foreground_templates": ["{{ if .Code }}p:false{{ end }}"],
          "template": "\udb81\udd1f {{ .FormattedMs }} ",
          "properties": {
            "threshold": 500,
            "style": "austin"
          }
        }
      ]
    },
    {
      "alignment": "left",
      "newline": true,
      "type": "prompt",
      "segments": [
        {
          "style": "plain",
          "foreground": "p:rosewater",
          "foreground_templates": ["{{ if gt .Code 0 }}p:false{{ end }}"],
          "template": "\u276f",
          "type": "text"
        }
      ]
    }
  ],

  "final_space": true,
  "version": 3
}
```

and this is .bashrc (i know its so bad but i will sort it later)
```bash
#!/bin/bash
[[ $- == *i* ]] && source -- /home/y2w8/.local/share/blesh/ble.sh --attach=none
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
	PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

export PATH_TO_FX=/opt/javafx-sdk-24.0.1/lib
export JAVA_HOME=/usr/lib/jvm/jdk-17.0.12-oracle-x64
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$PATH:/opt/gradle/gradle-9.0.0/bin

export EDITOR=nvim
# xhost +si:localuser:root
# neofetch

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi
unset rc

# Make sh file global in bin
mkglobal() {
	if [ -z "$1" ] || [ -z "$2" ]; then
		echo "Usage: mkglobal <script> <command-name>"
		return 1
	fi
	sudo cp "$1" "/usr/local/bin/$2" &&
		sudo chmod +x "/usr/local/bin/$2" &&
		echo "Installed '$2' globally in /usr/local/bin/"
}

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	/home/y2w8/Downloads/yazi-x86_64-unknown-linux-gnu/yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd <"$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export PS1=""
export PROMPT_COMMAND=""
eval "$(oh-my-posh init bash --config /home/y2w8/.config/ohmyposh/mocha.omp.json)"
eval "$(zoxide init --cmd cd bash)"
export PATH=$PATH:/usr/lib64/qt6/bin
export QTWEBENGINE_DISABLE_SANDBOX=1
export QTWEBENGINE_USE_VULKAN=1
bleopt color_scheme=catppuccin_mocha
. "$HOME/.cargo/env"
[[ ! ${BLE_VERSION-} ]] || ble-attach
```

thanks for your time that you spend to help me

**Comment by akinomyoga** [comment]
It seems this has been reported to Bash last month [1], but this hasn't yet been fixed in the `devel` branch of Bash.

- [1] https://lists.gnu.org/archive/html/bug-bash/2025-08/msg00107.html

**Comment by y2w8** [comment]
then what do i do
i make 
export PROMPT_COMMAND=_omp_hook
export PS1="$(_omp_get_primary)"
and when i open the terminal and the problem still there and it says 
```bash
bash: _omp_get_primary: command not found...
 ~ 
 ~ 
❯ 
```

**Comment by akinomyoga** [comment]
This seems to be a general problem of `ble.sh` when the number of lines in the prompt changes dynamically.

However, in your case, you should actually use `bleopt prompt_ruler`. You can remove `"newline": true,` from the first segment in your OMP configuration, and instead set `bleopt prompt_ruler=$'\n'` in `~/.blerc`.

**Comment by y2w8** [comment]
it workss thank u 
i have another problem in ohmyposh 
its second prompt does not work because of ble.sh multi line is there a way to make them work together because multi line is really helpful feature if not then how to disable multi line
this my secondary prompt
```json
  "secondary_prompt": {
    "style": "plain",
    "foreground": "p:rosewater",
    "template": "\u276f\u276f ",
    "type": "text"
  },
```
